In [2]:

import numpy as np
import pandas as pd

A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

B = np.array([[6],
              [-11],
              [-3]])

print("--- Matrix A Shape & Dimensions ---")
print("Shape of A:", A.shape)
print("Dimensions:", A.ndim)

print("\nElement at Row 2, Column 3 (Index 1, 2):", A[1, 2])

print("\nElement-wise A * A:\n", A * A)

C = np.dot(A, A)
print("\nMatrix Multiplication (A @ A):\n", C)




print("\n--- Solving Linear Equations (A * X = B) ---")


A_inv = np.linalg.inv(A)
X_inv = np.dot(A_inv, B)
print("Solution using Inverse (x, y, z):\n", X_inv)


X_solve = np.linalg.solve(A, B)
print("\nSolution using np.linalg.solve (x, y, z):\n", X_solve)


data_matrix = np.array([
    [85, 90, 78],
    [60, 70, 65],
    [92, 95, 98],
    [75, 80, 70],
    [50, 55, 60]
])

student_names = ['katy', 'manar', 'rena', 'lady', 'mai']
subjects = ['Math_LinearAlgebra', 'Statistics', 'Python_Programming']

df = pd.DataFrame(data=data_matrix, index=student_names, columns=subjects)

print("\n--- Pandas DataFrame ---")
print(df)

print("\nrena's Grades (using loc):")
print(df.loc['rena'])

print("\nStatistics Grade for manr (Row Index 1, Col Index 1 using iloc):")
print(df.iloc[1, 1])

print("\n--- Summary Statistics (Mean per Subject) ---")
print(df.mean(axis=0))

df['Total_Score'] = df.sum(axis=1)
print("\n--- Final Table with Total Scores ---")
print(df)

--- Matrix A Shape & Dimensions ---
Shape of A: (3, 3)
Dimensions: 2

Element at Row 2, Column 3 (Index 1, 2): 2

Element-wise A * A:
 [[4 1 1]
 [9 1 4]
 [4 1 4]]

Matrix Multiplication (A @ A):
 [[  3   0  -2]
 [ -7   0   5]
 [-11  -1   8]]

--- Solving Linear Equations (A * X = B) ---
Solution using Inverse (x, y, z):
 [[ -6.]
 [  7.]
 [-11.]]

Solution using np.linalg.solve (x, y, z):
 [[ -6.]
 [  7.]
 [-11.]]

--- Pandas DataFrame ---
       Math_LinearAlgebra  Statistics  Python_Programming
katy                   85          90                  78
manar                  60          70                  65
rena                   92          95                  98
lady                   75          80                  70
mai                    50          55                  60

rena's Grades (using loc):
Math_LinearAlgebra    92
Statistics            95
Python_Programming    98
Name: rena, dtype: int64

Statistics Grade for manr (Row Index 1, Col Index 1 using iloc):
70

--- Summary