In [ ]:


import numpy as np
# section 1
print("\n section 1:")

# Problem 1
M = np.array([
    [4, -2, 7, 0],
    [1, 9, 3, -5],
    [8, 6, -1, 2]
])
print("\nProblem 1:")
print("Dimensions (shape):", M.shape)
print("m1,3 =", M[0, 2])
print("m2,4 =", M[1, 3])
print("m3,2 =", M[2, 1])


# Problem 2
print("\nProblem 2:")
A = np.array([[3, 5], [-1, 4]])
B = np.array([[0, -2], [7, 1]])
C = np.array([[1, 2, 3], [4, 5, 6]])

print("A + B:\n", A + B)
print("A - B:\n", A - B)

if A.shape == C.shape:
    print("A + C:\n", A + C)
else:
    print("Cannot compute A + C: Dimensions do not match!")


    # Problem 3
    print("\nProblem 3:")
    import numpy as np
    X = np.array([[2, -1], [3, 0]])
Y = np.array([[1, 4], [-2, 5]])

print("3X (Scalar):\n", 3 * X)
print("X * Y (Element-wise):\n", X * Y)
print("X . Y (Dot Product):\n", np.dot(X, Y))

  # Problem 4
print("\nProblem 4:")

K = np.array([[5, 2], [3, 4]])
print("Transpose (K^T):\n", K.T)
print("Determinant det(K):", np.linalg.det(K))
print("Inverse (K^-1):\n", np.linalg.inv(K))

  # Problem 5
print("\nProblem 5:")

A = np.array([[2, 3], [4, -1]])
B = np.array([13, 5])
solution = np.linalg.solve(A, B)
print("Solution -> x =", solution[0], ", y =", solution[1])








 section 1:

Problem 1:
Dimensions (shape): (3, 4)
m1,3 = 7
m2,4 = -5
m3,2 = 6

Problem 2:
A + B:
 [[3 3]
 [6 5]]
A - B:
 [[ 3  7]
 [-8  3]]
Cannot compute A + C: Dimensions do not match!

Problem 3:
3X (Scalar):
 [[ 6 -3]
 [ 9  0]]
X * Y (Element-wise):
 [[ 2 -4]
 [-6  0]]
X . Y (Dot Product):
 [[ 4  3]
 [ 3 12]]

Problem 4:
Transpose (K^T):
 [[5 3]
 [2 4]]
Determinant det(K): 13.999999999999996
Inverse (K^-1):
 [[ 0.28571429 -0.14285714]
 [-0.21428571  0.35714286]]

Problem 5:
Solution -> x = 2.0 , y = 3.0


In [ ]:

import numpy as np
# section 2
print("\nsection 2:")
# Problem 1
print("\nProblem 1:")

A = np.array([[2, 3], [4, -1]])
B = np.array([13, 5])

solution = np.linalg.solve(A, B)
print("Solution -> x =", solution[0], ", y =", solution[1])

# Problem 2
print("\nProblem 2:")
import statistics as st

data = [120, 150, 130, 180, 150, 200, 110, 160]

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Mode:", st.mode(data))









section 2:

Problem 1:
Solution -> x = 2.0 , y = 3.0

Problem 2:
Mean: 150.0
Median: 150.0
Mode: 150
